#============================================================================================
# https://github.com/P3TERX/Actions-OpenWrt
# https://github.com/ophub/amlogic-s9xxx-openwrt
# https://github.com/3wlh/Actions-OpenWrt
# Description: Build OpenWrt
#============================================================================================

name: OpenWrt View Config

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "openwrt-main"
        type: choice
        options:
          - openwrt-main
          - lede-master
          - immortalwrt-master

env:
  TZ: Asia/Shanghai
  UPLOAD_CONFIG: true

  
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install cmake curl wget git
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo rm -rf ~/{.cargo,.dotnet,.rustup}
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code [ ${{ inputs.source_branch }} ]
      working-directory: /workdir
      run: |
        df -hT $PWD
        # Set up compilation source code
        if [[ "${{ inputs.source_branch }}" == *"openwrt"* ]]; then
            REPO_URL="https://github.com/openwrt/openwrt"
            REPO_BRANCH="main"
            TAGS_NAME="official"
        elif [[ "${{ inputs.source_branch }}" == *"lede"* ]]; then
            REPO_URL="https://github.com/coolsnowwolf/lede"
            REPO_BRANCH="master"
            TAGS_NAME="lede"
        elif [[ "${{ inputs.source_branch }}" == *"immortalwrt"* ]]; then
            REPO_URL="https://github.com/immortalwrt/immortalwrt"
            REPO_BRANCH="master"
            TAGS_NAME="immortalwrt"
        else
            echo "Unknown source code repository."
              exit 1
          fi
        # Clone source code
        git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        echo "REPO_URL=${REPO_URL}" >> ${GITHUB_OUTPUT}
        echo "TAGS_NAME=${TAGS_NAME}" >> ${GITHUB_OUTPUT}
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Download Config
      id: config
      run: |
        cd openwrt
        make defconfig
        echo -e "$(cat .config)"
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Organize Files
      id: files
      run: |
        cd openwrt
        sudo mkdir Configs
        sudo chown $USER:$GROUPS Configs
        cat .config | xargs -i echo {} > Configs/config
        echo "SOURCE_NAME=${TAGS_NAME}" >> $GITHUB_ENV
        echo "FILES_DIR=${GITHUB_WORKSPACE}/openwrt/Configs" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload Config directory
      uses: actions/upload-artifact@main
      if: env.UPLOAD_CONFIG == 'true' && !cancelled()
      with:
        name: ${{ env.SOURCE_NAME }}_Config-${{ env.FILE_DATE }}
        path: openwrt/Configs
